language: go
go:
  - 1.4
  - tip
env:
  - GOARCH=amd64
before_install:
  - sed -E -i 's|git://github.com/([A-Za-z0-9_]+)/tsuru.git|https://github.com/\1/tsuru|g' .git/config
  - cat .git/config
  - sudo apt-get update -qq > apt-get.out 2>&1  || (cat apt-get.out && exit 1)
  - sudo apt-get install bzr git -qq > apt-get.out 2>&1 || (cat apt-get.out && exit 1)
  - sudo /etc/init.d/postgresql stop
  - sudo /etc/init.d/mysql stop
  - mongod --version
  - sudo /etc/init.d/mongodb stop
  - sudo sed -i 's/^journal=true//' /etc/mongodb.conf
  - echo "nojournal = true" | sudo tee -a /etc/mongodb.conf
  - echo "smallfiles = true" | sudo tee -a /etc/mongodb.conf
  - cat /etc/mongodb.conf
  - sudo /etc/init.d/mongodb start
os:
  - linux
  - osx
  - windows
install:
  - export PATH="$HOME/gopath/bin:$PATH"
before_script:
  # Check baseline memory usage; for compare with after_failure when OOM occurs
  - free
  - vmstat
script:
  - make test install
after_failure:
after_success:
notifications:
  email:
    recipients:
      - drew.wells00@gmail.com
    on_success: change
    on_failure: always
